### ISSUE TITLE
Network Error?

### ISSUE THREAD

**Issue by SirWoofie** [Lunatrius/LunatriusCore#14]
Reproduced the problem, both times it caused my ethernet connection to fail. Interesting problem, feel free to close this if it is just a pointless PC error.
Seems like LunatriusCore caused a problem! At the bottom, Aroma1997Core tells me to check my internet, which is functioning again.

Affecting area of log

```
[21:44:24] [LunatriusCore Version Check/ERROR] [LunatriusCore]: Something went wrong!
java.net.ConnectException: Connection timed out: connect
	at java.net.TwoStacksPlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_60]
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[?:1.8.0_60]
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[?:1.8.0_60]
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_60]
	at java.net.PlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_60]
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:1.8.0_60]
	at java.net.Socket.connect(Unknown Source) ~[?:1.8.0_60]
	at java.net.Socket.connect(Unknown Source) ~[?:1.8.0_60]
	at sun.net.NetworkClient.doConnect(Unknown Source) ~[?:1.8.0_60]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:1.8.0_60]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:1.8.0_60]
	at sun.net.www.http.HttpClient.<init>(Unknown Source) ~[?:1.8.0_60]
	at sun.net.www.http.HttpClient.New(Unknown Source) ~[?:1.8.0_60]
	at sun.net.www.http.HttpClient.New(Unknown Source) ~[?:1.8.0_60]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source) ~[?:1.8.0_60]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[?:1.8.0_60]
	at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source) ~[?:1.8.0_60]
	at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source) ~[?:1.8.0_60]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_60]
	at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source) ~[?:1.8.0_60]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[?:1.8.0_60]
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source) ~[?:1.8.0_60]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_60]
	at sun.net.www.protocol.http.HttpURLConnection.access$200(Unknown Source) ~[?:1.8.0_60]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source) ~[?:1.8.0_60]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source) ~[?:1.8.0_60]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_60]
	at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source) ~[?:1.8.0_60]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_60]
	at java.net.URL.openStream(Unknown Source) ~[?:1.8.0_60]
	at com.github.lunatrius.core.version.VersionChecker$1.run(VersionChecker.java:79) [VersionChecker$1.class:?]
[21:44:32] [Aroma1997Core VersionChecking/ERROR] [Aroma1997Core]: Failed to do VersionChecking. Check your network connection.
```

**Comment by Lunatrius** [comment]
I'm pretty sure that's your internet connection going down. There should be no way for a simple HTTP request to take down the ethernet connection - unless there's a bug in the JVM.

Also both mods fail for the same reason - the *connection timed out*. Aroma1997Core prints it as a simple message, where as LunatriusCore includes the stacktrace so that debugging can be easier.

Another possibility could be that your firewall/router is blocking those requests. Also, I'd try to run Minecraft with just LunatriusCore in a separate instance to see if the same issue happens again.

**Comment by SirWoofie** [comment]
One problem may be because of the fairly outdated version I'm using, which is from the base pack for my custom modpack, Resonant Rise 3. It causes many issues so most mods are updated from the RR3 base pack I used, but LunatriusCore worked fine until I got my Ethernet set up. (Never caused this problem)

Tried with just LunatriusCore in a separate modpack and it didn't have the problem. Either whatever I did recently fixed the issue, or I have an incompatibility that is too small to worry about. Just thought you could know in case there was a larger problem.

On a side note: FireFox spellcheck thinks LunatriusCore should be Dominatrices. Weird.

**Comment by Lunatrius** [comment]
The only other possibility I can think of is that some mod is trying to disable network connections for version checks. Given the amount of core mods out there I wouldn't be surprised if that was the case (at least in 1.8 the version checking is centralized so it can be turned off globally for everything).
