### ISSUE TITLE
Version Check Error, server console messages

### ISSUE THREAD

**Issue by APolarBaer** [Lunatrius/LunatriusCore#17]
```
[23:42:18] [LunatriusCore Version Check/ERROR] [LunatriusCore]: Something went wrong!
java.net.UnknownHostException: mc.lunatri.us
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_101]
        at java.net.PlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_101]
        at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:1.8.0_101]
        at java.net.Socket.connect(Unknown Source) ~[?:1.8.0_101]
        at java.net.Socket.connect(Unknown Source) ~[?:1.8.0_101]
        at sun.net.NetworkClient.doConnect(Unknown Source) ~[?:1.8.0_101]
        at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:1.8.0_101]
        at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:1.8.0_101]
        at sun.net.www.http.HttpClient.<init>(Unknown Source) ~[?:1.8.0_101]
        at sun.net.www.http.HttpClient.New(Unknown Source) ~[?:1.8.0_101]
        at sun.net.www.http.HttpClient.New(Unknown Source) ~[?:1.8.0_101]
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source) ~[?:1.8.0_101]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[?:1.8.0_101]
        at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source) ~[?:1.8.0_101]
        at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source) ~[?:1.8.0_101]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_101]
        at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source) ~[?:1.8.0_101]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[?:1.8.0_101]
        at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source) ~[?:1.8.0_101]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_101]
        at sun.net.www.protocol.http.HttpURLConnection.access$200(Unknown Source) ~[?:1.8.0_101]
        at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source) ~[?:1.8.0_101]
        at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source) ~[?:1.8.0_101]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_101]
        at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source) ~[?:1.8.0_101]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_101]
        at com.github.lunatrius.core.version.VersionChecker$1.run(VersionChecker.java:54) [VersionChecker$1.class:?]
```

**Comment by Lunatrius** [comment]
It shouldn't be spamming the console, there should be only one stack trace.

The DNS is currently offline because the host's domain expired, I'm currently trying to contract the host.

**Comment by APolarBaer** [comment]
Not as much spam as like 3 times during startup, my apologies

**Comment by APolarBaer** [comment]
Changed the title to reflect the issue better, again my apologies. Good luck with your donation issues

**Comment by Lunatrius** [comment]
The website is back up.
