### ISSUE TITLE
crash on 1.12

### ISSUE THREAD

**Issue by thevipe** [Lunatrius/LunatriusCore#26]
[crash-2019-01-08_10.58.01-client.txt](https://github.com/Lunatrius/LunatriusCore/files/2737729/crash-2019-01-08_10.58.01-client.txt)
I'm not sure if it is my side or the mod itself but I do no it shouldn't be me with my 1080ti and happens when I load large schematics

**Comment by ghost** [comment]
```
	at com.github.lunatrius.schematica.client.renderer.chunk.container.SchematicChunkRenderContainerVbo.func_178001_a(SchematicChunkRenderContainerVbo.java:28)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderBlockLayer(RenderSchematic.java:802)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.func_174977_a(RenderSchematic.java:793)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderWorld(RenderSchematic.java:354)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderSchematic(RenderSchematic.java:278)
	
```

This is an issue with Schematica. Not LunatriusCore.
