### ISSUE TITLE
Issue 1.8

### ISSUE THREAD

**Issue by Grumpyh** [Lunatrius/LunatriusCore#7]
**Mod name:** Schematica 
**Mod version:** 1.7.5.113
**Forge version:** 11.14.1.1306
**Operating system:** Windows
**Modlist**
  * VersionChecker

```
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2/6/15 8:14 PM
Description: Unexpected error

java.lang.IllegalAccessError: tried to access method net.minecraft.client.renderer.ViewFrustum.func_178161_a(Lnet/minecraft/util/BlockPos;)Lnet/minecraft/client/renderer/chunk/RenderChunk; from class com.github.lunatrius.schematica.client.renderer.RenderSchematic
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.func_174970_a(RenderSchematic.java:479)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderWorld(RenderSchematic.java:269)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderSchematic(RenderSchematic.java:244)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.onRenderWorldLast(RenderSchematic.java:187)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_21_RenderSchematic_onRenderWorldLast_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:271)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1397)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1207)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1032)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1049)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
	at org.multimc.EntryPoint.listen(EntryPoint.java:165)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.func_174970_a(RenderSchematic.java:479)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderWorld(RenderSchematic.java:269)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderSchematic(RenderSchematic.java:244)
	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.onRenderWorldLast(RenderSchematic.java:187)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_21_RenderSchematic_onRenderWorldLast_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:271)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1397)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1207)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Trickshotz00'/397, l='MpServer', x=-140.20, y=73.17, z=251.24]]
	Chunk stats: MultiplayerChunkCache: 576, 576
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: -140.00,64.00,256.00 - World: (-140,64,256), Chunk: (at 4,4,0 in -9,16; contains blocks -144,0,256 to -129,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 3021 game time, 3021 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 138 total; [EntityBat['Bat'/275, l='MpServer', x=-126.38, y=13.97, z=232.19], EntityCreeper['Creeper'/274, l='MpServer', x=-124.34, y=10.00, z=218.28], EntitySpider['Spider'/279, l='MpServer', x=-113.72, y=31.00, z=242.69], EntityEnderman['Enderman'/278, l='MpServer', x=-115.94, y=31.00, z=253.53], EntityCreeper['Creeper'/277, l='MpServer', x=-123.50, y=33.00, z=236.50], EntityItem['item.tile.torch'/276, l='MpServer', x=-122.59, y=33.00, z=228.88], EntityItem['item.tile.torch'/283, l='MpServer', x=-125.13, y=26.00, z=269.72], EntityCreeper['Creeper'/282, l='MpServer', x=-113.63, y=31.00, z=243.91], EntitySkeleton['Skeleton'/281, l='MpServer', x=-119.84, y=31.00, z=256.28], EntitySkeleton['Skeleton'/280, l='MpServer', x=-117.50, y=31.00, z=250.50], EntityMinecartChest['container.minecart'/287, l='MpServer', x=-122.50, y=26.06, z=298.50], EntityCreeper['Creeper'/286, l='MpServer', x=-124.50, y=35.00, z=257.50], EntityCreeper['Creeper'/285, l='MpServer', x=-126.50, y=26.00, z=260.50], EntityZombie['Zombie'/284, l='MpServer', x=-122.31, y=24.00, z=262.28], EntityCreeper['Creeper'/258, l='MpServer', x=-140.50, y=24.00, z=268.50], EntitySkeleton['Skeleton'/259, l='MpServer', x=-143.50, y=25.00, z=259.50], EntitySpider['Spider'/256, l='MpServer', x=-123.69, y=24.11, z=262.69], EntityCreeper['Creeper'/257, l='MpServer', x=-143.38, y=24.00, z=260.97], EntityCreeper['Creeper'/262, l='MpServer', x=-131.75, y=31.00, z=278.84], EntityChicken['Chicken'/263, l='MpServer', x=-123.63, y=68.00, z=272.50], EntityItem['item.tile.torch'/260, l='MpServer', x=-132.78, y=31.00, z=278.66], EntitySkeleton['Skeleton'/261, l='MpServer', x=-138.84, y=31.00, z=277.41], EntityChicken['Chicken'/266, l='MpServer', x=-137.50, y=68.00, z=287.75], EntityChicken['Chicken'/264, l='MpServer', x=-142.06, y=68.00, z=280.31], EntityCreeper['Creeper'/572, l='MpServer', x=-220.50, y=43.00, z=219.50], EntityZombie['Zombie'/265, l='MpServer', x=-138.44, y=32.00, z=299.97], EntityZombie['Zombie'/270, l='MpServer', x=-125.50, y=33.00, z=183.50], EntitySpider['Spider'/271, l='MpServer', x=-120.75, y=34.19, z=184.31], EntityItem['item.tile.flower1.dandelion'/305, l='MpServer', x=-90.22, y=64.00, z=213.66], EntityItem['item.item.seeds'/304, l='MpServer', x=-87.63, y=64.00, z=211.91], EntitySpider['Spider'/307, l='MpServer', x=-93.50, y=30.00, z=230.50], EntityBat['Bat'/306, l='MpServer', x=-81.58, y=24.59, z=220.56], EntityMinecartChest['container.minecart'/309, l='MpServer', x=-84.50, y=30.00, z=242.63], EntityChicken['Chicken'/308, l='MpServer', x=-80.38, y=67.00, z=226.50], EntityChicken['Chicken'/311, l='MpServer', x=-83.47, y=69.00, z=259.25], EntityChicken['Chicken'/310, l='MpServer', x=-83.38, y=69.00, z=251.66], EntityChicken['Chicken'/312, l='MpServer', x=-86.34, y=68.00, z=268.50], EntityChicken['Chicken'/319, l='MpServer', x=-70.78, y=62.69, z=210.91], EntityBat['Bat'/318, l='MpServer', x=-68.28, y=33.10, z=220.09], EntityBat['Bat'/288, l='MpServer', x=-121.72, y=26.78, z=287.34], EntitySkeleton['Skeleton'/291, l='MpServer', x=-96.50, y=30.00, z=233.50], EntitySquid['Squid'/292, l='MpServer', x=-98.56, y=60.34, z=252.28], EntityItem['item.item.seeds'/293, l='MpServer', x=-102.91, y=63.00, z=253.75], EntityItem['item.item.seeds'/294, l='MpServer', x=-103.84, y=63.00, z=252.44], EntityItem['item.tile.rail'/295, l='MpServer', x=-97.50, y=29.00, z=260.75], EntityItem['item.tile.rail'/296, l='MpServer', x=-96.88, y=32.00, z=263.25], EntitySquid['Squid'/297, l='MpServer', x=-99.56, y=58.00, z=262.72], EntityItem['item.item.seeds'/303, l='MpServer', x=-85.13, y=63.00, z=222.66], EntityChicken['Chicken'/322, l='MpServer', x=-72.59, y=70.00, z=264.25], EntityChicken['Chicken'/323, l='MpServer', x=-76.53, y=80.00, z=326.03], EntityChicken['Chicken'/320, l='MpServer', x=-68.84, y=62.53, z=212.25], EntityZombie['Zombie'/93, l='MpServer', x=-210.44, y=36.00, z=209.47], EntityZombie['Zombie'/92, l='MpServer', x=-213.41, y=34.00, z=209.56], EntitySkeleton['Skeleton'/95, l='MpServer', x=-212.34, y=46.00, z=228.69], EntitySkeleton['Skeleton'/94, l='MpServer', x=-211.38, y=47.00, z=229.09], EntityChicken['Chicken'/89, l='MpServer', x=-219.34, y=68.00, z=174.44], EntityCreeper['Creeper'/91, l='MpServer', x=-212.72, y=43.56, z=203.28], EntitySkeleton['Skeleton'/90, l='MpServer', x=-214.56, y=45.00, z=191.81], EntityCreeper['Creeper'/100, l='MpServer', x=-213.50, y=44.00, z=300.00], EntityChicken['Chicken'/99, l='MpServer', x=-214.72, y=66.00, z=280.50], EntityZombie['Zombie'/96, l='MpServer', x=-213.22, y=47.00, z=228.41], EntityChicken['Chicken'/97, l='MpServer', x=-213.72, y=66.00, z=274.97], EntitySkeleton['Skeleton'/591, l='MpServer', x=-129.50, y=36.00, z=269.50], EntityChicken['Chicken'/116, l='MpServer', x=-192.41, y=67.00, z=297.31], EntityZombie['Zombie'/115, l='MpServer', x=-204.50, y=40.00, z=194.50], EntityBat['Bat'/114, l='MpServer', x=-201.81, y=46.09, z=185.50], EntityChicken['Chicken'/112, l='MpServer', x=-198.69, y=69.00, z=171.31], EntityCreeper['Creeper'/127, l='MpServer', x=-180.50, y=15.00, z=212.50], EntityChicken['Chicken'/137, l='MpServer', x=-189.38, y=66.00, z=303.53], EntityChicken['Chicken'/136, l='MpServer', x=-169.66, y=65.00, z=286.59], EntityPlayerSP['Trickshotz00'/397, l='MpServer', x=-140.20, y=73.17, z=251.24], EntityCreeper['Creeper'/129, l='MpServer', x=-178.63, y=16.00, z=208.97], EntityCreeper['Creeper'/128, l='MpServer', x=-178.50, y=15.00, z=214.50], EntityCreeper['Creeper'/131, l='MpServer', x=-197.16, y=46.00, z=299.19], EntityBat['Bat'/130, l='MpServer', x=-178.53, y=19.81, z=244.25], EntityChicken['Chicken'/133, l='MpServer', x=-189.38, y=67.00, z=295.28], EntityChicken['Chicken'/132, l='MpServer', x=-192.56, y=65.00, z=308.34], EntityChicken['Chicken'/135, l='MpServer', x=-187.63, y=67.00, z=290.09], EntityChicken['Chicken'/134, l='MpServer', x=-184.50, y=67.00, z=291.50], EntityCow['Cow'/171, l='MpServer', x=-162.84, y=68.00, z=208.13], EntityCow['Cow'/170, l='MpServer', x=-161.72, y=68.00, z=220.34], EntityItem['item.tile.torch'/169, l='MpServer', x=-162.84, y=37.00, z=209.50], EntityItem['item.tile.rail'/168, l='MpServer', x=-161.13, y=34.00, z=195.75], EntityZombie['Zombie'/175, l='MpServer', x=-168.91, y=12.00, z=245.47], EntityItem['item.item.seeds'/174, l='MpServer', x=-163.13, y=65.00, z=232.50], EntityBat['Bat'/173, l='MpServer', x=-160.25, y=21.75, z=231.25], EntityBat['Bat'/172, l='MpServer', x=-177.56, y=10.88, z=234.53], EntityItem['item.tile.rail'/163, l='MpServer', x=-163.88, y=34.00, z=194.75], EntityItem['item.tile.rail'/162, l='MpServer', x=-163.88, y=34.00, z=195.72], EntityItem['item.tile.torch'/167, l='MpServer', x=-163.56, y=34.00, z=206.22], EntityItem['item.tile.rail'/166, l='MpServer', x=-161.13, y=34.00, z=204.22], EntityItem['item.tile.rail'/165, l='MpServer', x=-163.66, y=34.00, z=206.41], EntityBat['Bat'/164, l='MpServer', x=-162.47, y=36.10, z=195.75], EntitySquid['Squid'/186, l='MpServer', x=-167.41, y=60.28, z=306.47], EntityChicken['Chicken'/185, l='MpServer', x=-171.50, y=62.66, z=305.28], EntityBat['Bat'/178, l='MpServer', x=-169.16, y=12.31, z=241.44], EntityItem['item.tile.gravel'/179, l='MpServer', x=-160.16, y=32.00, z=250.78], EntityBat['Bat'/176, l='MpServer', x=-168.66, y=12.34, z=245.47], EntityZombie['Zombie'/177, l='MpServer', x=-170.09, y=14.00, z=240.47], EntityCreeper['Creeper'/182, l='MpServer', x=-159.34, y=30.00, z=264.72], EntityChicken['Chicken'/183, l='MpServer', x=-166.44, y=64.00, z=270.75], EntityItem['item.tile.gravel'/180, l='MpServer', x=-160.41, y=32.00, z=251.88], EntityItem['item.tile.gravel'/181, l='MpServer', x=-160.16, y=32.00, z=254.28], EntityCreeper['Creeper'/220, l='MpServer', x=-148.50, y=27.00, z=251.50], EntityZombie['Zombie'/221, l='MpServer', x=-145.72, y=21.53, z=253.69], EntityZombie['Zombie'/222, l='MpServer', x=-147.31, y=33.00, z=253.69], EntityItem['item.tile.torch'/223, l='MpServer', x=-159.47, y=27.00, z=261.53], EntityBat['Bat'/216, l='MpServer', x=-155.91, y=21.10, z=229.25], EntityBat['Bat'/217, l='MpServer', x=-164.00, y=15.94, z=240.63], EntityBat['Bat'/218, l='MpServer', x=-151.88, y=28.10, z=241.75], EntityBat['Bat'/219, l='MpServer', x=-133.69, y=27.63, z=256.63], EntityRabbit['Rabbit'/212, l='MpServer', x=-151.50, y=69.00, z=213.25], EntityCow['Cow'/213, l='MpServer', x=-160.00, y=68.00, z=217.09], EntityCow['Cow'/214, l='MpServer', x=-161.81, y=68.00, z=212.50], EntityBat['Bat'/215, l='MpServer', x=-156.25, y=19.10, z=226.59], EntityCow['Cow'/208, l='MpServer', x=-149.19, y=69.00, z=202.88], EntityCow['Cow'/209, l='MpServer', x=-158.50, y=69.00, z=206.50], EntityCow['Cow'/210, l='MpServer', x=-159.81, y=69.00, z=207.69], EntityCow['Cow'/211, l='MpServer', x=-160.59, y=68.00, z=212.50], EntitySquid['Squid'/235, l='MpServer', x=-163.91, y=62.00, z=305.47], EntitySkeleton['Skeleton'/234, l='MpServer', x=-152.50, y=48.00, z=288.91], EntityCreeper['Creeper'/233, l='MpServer', x=-152.00, y=48.00, z=296.56], EntitySkeleton['Skeleton'/232, l='MpServer', x=-153.59, y=47.00, z=298.69], EntityChicken['Chicken'/231, l='MpServer', x=-156.34, y=67.00, z=284.53], EntityChicken['Chicken'/230, l='MpServer', x=-158.81, y=67.00, z=285.06], EntityChicken['Chicken'/229, l='MpServer', x=-149.50, y=67.00, z=286.50], EntityChicken['Chicken'/228, l='MpServer', x=-149.50, y=68.00, z=284.50], EntitySpider['Spider'/227, l='MpServer', x=-155.31, y=53.00, z=285.50], EntityCreeper['Creeper'/226, l='MpServer', x=-149.31, y=51.00, z=282.50], EntityZombie['Zombie'/225, l='MpServer', x=-149.84, y=36.00, z=258.19], EntitySkeleton['Skeleton'/224, l='MpServer', x=-152.53, y=32.00, z=270.06], EntityItem['item.tile.torch'/254, l='MpServer', x=-131.53, y=31.00, z=268.97], EntityCreeper['Creeper'/255, l='MpServer', x=-144.50, y=24.00, z=271.00], EntityZombie['Zombie'/252, l='MpServer', x=-136.94, y=20.00, z=255.53], EntityZombie['Zombie'/253, l='MpServer', x=-132.06, y=21.00, z=261.47], EntityRabbit['Rabbit'/250, l='MpServer', x=-139.66, y=68.00, z=203.34], EntityItem['item.tile.rail'/251, l='MpServer', x=-137.88, y=33.00, z=211.06], EntityRabbit['Rabbit'/249, l='MpServer', x=-146.78, y=69.00, z=198.75]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:350)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2489)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:374)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
	at org.multimc.EntryPoint.listen(EntryPoint.java:165)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.7.0_72, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 163301840 bytes (155 MB) / 697827328 bytes (665 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.10 FML v8.0.26.1306 Minecraft Forge 11.14.1.1306 6 mods loaded, 6 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{8.0.26.1306} [Forge Mod Loader] (forge-1.8-11.14.1.1306-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{11.14.1.1306} [Minecraft Forge] (forge-1.8-11.14.1.1306-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	LunatriusCore{1.1.2.22} [LunatriusCore] (1ee43350-508d-40a6-8441-ee13080c8c8a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Schematica{1.7.5.113} [Schematica] (51316626-1722-4720-b654-a809e9730308.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	VersionChecker{1.2.0} [Version Checker] (fe855f92-c1f9-416e-aa11-eab4d5d83fa8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Launched Version: 1.8
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 760/PCIe/SSE2 GL version 4.5.0 NVIDIA 347.25, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
```

**Comment by Lunatrius** [comment]
1. Wrong repository
2. You used the wrong formatting (fixed it)
3. You didn't read the [FAQ](https://github.com/Lunatrius/Schematica/wiki/Frequently-Asked-Questions#javalangillegalaccesserror-tried-to-access-method--from-class-)

I have no idea where you got the mods from, but I've never named my mods `51316626-1722-4720-b654-a809e9730308.jar`. Go re-download them from https://mods.io/

**Comment by Grumpyh** [comment]
I downloaded the mod from https://mods.io/

**Comment by Lunatrius** [comment]
Then try http://mc.lunatri.us/LunatriusCore / http://mc.lunatri.us/Schematica
